In [1]:
import pandas as pd
import random

# 데이터 전처리

In [2]:
# 학습용, 평가용 데이터 로드
train_df = pd.read_excel("./dataset/train_dataset00.xlsx")
test_df = pd.read_excel("./dataset/test_dataset00.xlsx")

In [3]:
# 벤치프레스의 70% 무게로 오버헤드 프레스 1RM 추가
train_df["press_1RM"] = (train_df["bench_press_1RM"] * 0.7).round(1)
test_df["press_1RM"] = (test_df["bench_press_1RM"] * 0.7).round(1)
train_df.head()

   성별    연령대  weight  squat_1RM  bench_press_1RM  deadlift_1RM  press_1RM
0  남성  35-39  107.70      320.0            215.0         310.0      150.5
1  남성  20-23   86.17      190.0            115.0         212.5       80.5
2  남성  24-34   64.90      160.0             95.0         182.5       66.5
3  남성  18-19   86.40      160.0            120.0         190.0       84.0
4  남성  24-34   92.55      220.0            140.0         225.0       98.0

In [4]:
# 운동 목표
# ENUM 값 목록
goals = [
    "최대 근력 키우기",
    "탄탄한 몸매 만들기",
    "체중 감량 성공하기",
    "운동 수행 능력 향상시키기",
    "지구력 향상시키기"
]

# 유저의 요청 샘플 목록
user_request = [
    "체중 감량도 병행 중이라 볼륨은 너무 많지 않았으면 해.",
    "하체 근력 향상에 포커스를 맞추고 싶어.",
    "요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.",
    "전반적인 근력과 체력을 같이 키우고 싶어.",
    "최근에 대회 준비를 시작했어. 강한 훈련이 필요해.",
    "근지구력을 높이고 싶어. 가능하면 액세서리 운동도 같이 포함해줘.",
    "운동 초보라 자세 위주로 천천히 하고 싶어.",
    "요즘 벤치가 안 늘어서 고민이야. 벤치 집중 루틴이 포함된 4주 5/3/1 프로그램 부탁해.",
    "건강 유지와 체력 향상이 목표야."
]

train_df["training_goal"] = [random.choice(goals) for _ in range(len(train_df))]
train_df["user_request"] = [random.choice(user_request) for _ in range(len(train_df))]
test_df["training_goal"] = [random.choice(goals) for _ in range(len(test_df))]
test_df["user_request"] = [random.choice(user_request) for _ in range(len(test_df))]

In [5]:
print(train_df["training_goal"].value_counts())
train_df.head()

training_goal
탄탄한 몸매 만들기        1028
체중 감량 성공하기        1020
지구력 향상시키기          966
운동 수행 능력 향상시키기     958
최대 근력 키우기          928
Name: count, dtype: int64

,성별,연령대,weight,squat_1RM,bench_press_1RM,deadlift_1RM,press_1RM,training_goal,user_request
0,남성,35-39,107.70,320.0,215.0,310.0,150.5,지구력 향상시키기,운동 초보라 자세 위주로 천천히 하고 싶어.
1,남성,20-23,86.17,190.0,115.0,212.5,80.5,체중 감량 성공하기,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.
2,남성,24-34,64.90,160.0,95.0,182.5,66.5,운동 수행 능력 향상시키기,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.
3,남성,18-19,86.40,160.0,120.0,190.0,84.0,최대 근력 키우기,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.
4,남성,24-34,92.55,220.0,140.0,225.0,98.0,지구력 향상시키기,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.

In [6]:
print(test_df["training_goal"].value_counts())
test_df.head()

training_goal
지구력 향상시키기         453
최대 근력 키우기         424
체중 감량 성공하기        416
운동 수행 능력 향상시키기    406
탄탄한 몸매 만들기        401
Name: count, dtype: int64

,성별,연령대,weight,squat_1RM,bench_press_1RM,deadlift_1RM,press_1RM,training_goal,user_request
0,남성,20-23,121.05,215.0,147.5,222.5,103.2,운동 수행 능력 향상시키기,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.
1,남성,24-34,107.40,270.0,180.0,290.0,126.0,최대 근력 키우기,근지구력을 높이고 싶어. 가능하면 액세서리 운동도 같이 포함해줘.
2,남성,24-34,97.80,197.5,142.5,210.0,99.8,지구력 향상시키기,요즘 벤치가 안 늘어서 고민이야. 벤치 집중 루틴이 포함된 4주 5/3/1 프로그램...
3,남성,24-34,84.80,260.0,167.5,260.0,117.2,탄탄한 몸매 만들기,건강 유지와 체력 향상이 목표야.
4,남성,24-34,86.70,185.0,142.5,225.0,99.8,지구력 향상시키기,체중 감량도 병행 중이라 볼륨은 너무 많지 않았으면 해.

In [7]:
user_prompts = []

for index, row in train_df.iterrows():
    gender = row["성별"]
    age = row["연령대"]
    weight = row["weight"]
    training_goal = row["training_goal"]
    squat_1RM = row["squat_1RM"]
    bench_press_1RM = row["bench_press_1RM"]
    deadlift_1RM = row["deadlift_1RM"]
    press_1RM = row["press_1RM"]


    instruction = row["user_request"] # 추후, 사용자 입력으로 확장

    input_data = {
        "성별": gender,
        "몸무게": weight,
        "squat_1RM": squat_1RM,
        "press_1RM": press_1RM,
        "bench_press_1RM": bench_press_1RM,
        "deadlift_1RM": deadlift_1RM
    }

    # user_prompt = f"""{instruction}
    
    # [input_data]
    # {input_data}
    # """
    user_prompts.append([instruction, input_data, ""])

In [8]:
# ["instruction", "input", "output"] 구조의 학습용 데이터 생성
train_df = pd.DataFrame(user_prompts)

cols = ["instruction", "input", "output"]
train_df.columns = cols

train_df.head()

,instruction,input,output
0,운동 초보라 자세 위주로 천천히 하고 싶어.,"{'성별': '남성', '몸무게': 107.7, 'squat_1RM': 320.0,...",
1,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.,"{'성별': '남성', '몸무게': 86.17, 'squat_1RM': 190.0,...",
2,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.,"{'성별': '남성', '몸무게': 64.9, 'squat_1RM': 160.0, ...",
3,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.,"{'성별': '남성', '몸무게': 86.4, 'squat_1RM': 160.0, ...",
4,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.,"{'성별': '남성', '몸무게': 92.55, 'squat_1RM': 220.0,...",

In [9]:
user_prompts = []

for index, row in test_df.iterrows():
    gender = row["성별"]
    age = row["연령대"]
    weight = row["weight"]
    training_goal = row["training_goal"]
    squat_1RM = row["squat_1RM"]
    bench_press_1RM = row["bench_press_1RM"]
    deadlift_1RM = row["deadlift_1RM"]
    press_1RM = row["press_1RM"]


    instruction = row["user_request"] # 추후, 사용자 입력으로 확장

    input_data = {
        "성별": gender,
        "몸무게": weight,
        "squat_1RM": squat_1RM,
        "press_1RM": press_1RM,
        "bench_press_1RM": bench_press_1RM,
        "deadlift_1RM": deadlift_1RM
    }

    # user_prompt = f"""{instruction}
    
    # [input_data]
    # {input_data}
    # """
    user_prompts.append([instruction, input_data, ""])

In [10]:
# ["instruction", "input", "output"] 구조의 평가용 데이터 생성
test_df = pd.DataFrame(user_prompts)

cols = ["instruction", "input", "output"]
test_df.columns = cols

test_df.head()

,instruction,input,output
0,요즘 허리가 안 좋아서 데드는 무리하지 않게 조절해줬으면 해.,"{'성별': '남성', '몸무게': 121.05, 'squat_1RM': 215.0...",
1,근지구력을 높이고 싶어. 가능하면 액세서리 운동도 같이 포함해줘.,"{'성별': '남성', '몸무게': 107.4, 'squat_1RM': 270.0,...",
2,요즘 벤치가 안 늘어서 고민이야. 벤치 집중 루틴이 포함된 4주 5/3/1 프로그램...,"{'성별': '남성', '몸무게': 97.8, 'squat_1RM': 197.5, ...",
3,건강 유지와 체력 향상이 목표야.,"{'성별': '남성', '몸무게': 84.8, 'squat_1RM': 260.0, ...",
4,체중 감량도 병행 중이라 볼륨은 너무 많지 않았으면 해.,"{'성별': '남성', '몸무게': 86.7, 'squat_1RM': 185.0, ...",

In [11]:
# 데이터 저장

train_df.to_excel("./dataset/train_dataset01.xlsx", index=False)
test_df.to_excel("./dataset/test_dataset01.xlsx", index=False)